# Generated by Django 5.0.1 on 2024-02-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_key', models.CharField(max_length=12, verbose_name='key')),
                ('title', models.CharField(max_length=250)),
                ('work_type', models.CharField(choices=[('painting', 'painting'), ('monotype', 'monotype'), ('tile', 'tile'), ('sculpture', 'sculpture')], max_length=100, verbose_name='type')),
                ('media', models.CharField(choices=[('oil on wood', 'oil on wood'), ('ink on paper', 'ink on paper'), ('watercolor', 'watercolor'), ('ceramic', 'ceramic')], max_length=100)),
                ('dims_height', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='height')),
                ('dims_width', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='width')),
                ('dims_depth', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='depth')),
                ('dims_unit', models.CharField(default='inches', max_length=20)),
                ('work_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('sold_to', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('inscription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('image_type', models.CharField(choices=[('primary', 'primary'), ('documentation only', 'documentation only'), ('detail', 'detail')], max_length=50)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.work', verbose_name='related image')),
            ],
        ),
    ]
