# Generated by Django 5.0.1 on 2024-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_image_image_url_image_image_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('sold', 'sold'), ('painted over', 'painted over')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('documentation only', 'documentation only'), ('detail', 'detail'), ('previous version', 'previous version')], max_length=50),
        ),
    ]
